os: linux
dist: xenial
sudo: required
git:
  depth: 3
addons:
  apt:
    update:
    - true
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install unzip
  - docker pull yshalsager/cyanogenmod:latest
before_script:
  - cd $HOME && mkdir twrp
  # download the TWRP Compressed Source Files from PhantomZone54's Release
  - wget -q https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.3.1-20200222/MinimalOmniRecovery-twrp-6.0-norepo-20200222.tar.xz
    -O $HOME/twrp.tar.xz
  - tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
script:
  # Replace your $$USERNAME$$, $$REPO_URL$$, $$BRAND$$, $$DEVICE$$
  - cd $HOME/twrp/ && git clone https://github.com/vinixast/twrp_device_apollo_x.git device/vernee/apollo_lite
  - cd $HOME/twrp/external && git clone https://github.com/mirror/busybox.git -b 1_31_stable
  - cd $HOME/twrp/
  - rm -rf bootable/recovery && git clone https://github.com/omnirom/android_bootable_recovery -b android-9.0 --depth 1 bootable/recovery
  # Get the Modified TWRPuilder Counter Part of the Tree
  - git clone https://github.com/ZeoRexDevs/device_generic_mtk_twrpbuilder device/generic/twrpbuilder
  - |
    docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/home/cmbuild/twrp/:rw,z" yshalsager/cyanogenmod bash << EOF
    cd /home/cmbuild/twrp/
    make clean
    export ALLOW_MISSING_DEPENDENCIES=TRUE
    source build/envsetup.sh && lunch omni_apollo_lite-eng && mka recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/apollo_lite/recovery.img $HOME/twrp/TWRP-$version-apollo_lite-$(date +"%Y%m%d")-Unofficial.img
  - cd $HOME/twrp/
  - curl -s --upload-file TWRP-$version-apollo_lite-$(date +"%Y%m%d")-Unofficial.img https://transfer.sh/ && echo ""
deploy:
  skip_cleanup: true
  provider: releases
  # The api_key will be loaded from the environment variables
  api_key: e8b4a4c903239b12beb2cf84607df936351977d1 
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: vinixast/twrp_device_apollo_x
    branch: master
branches:
  only:
  - master
  except:
  - /^(?i:untagged)-.*$/
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
